### ISSUE TITLE
1.18 support

### ISSUE THREAD

**Issue by maartenvr98** [tr7zw/Item-NBT-API#146]
Will this plugin be 1.18 compatible sometime?

I'm using NBT Api in my spawner plugin and currently its not working: 

`de.tr7zw.nbtapi.NbtApiException: Exception while getting an Itemstack's NBTCompound!
        at de.tr7zw.nbtapi.NBTReflectionUtil.getItemRootNBTTagCompound(NBTReflectionUtil.java:125) ~[MineableSpawners-4.4.0.jar:?]
        at de.tr7zw.nbtapi.NBTItem.getCompound(NBTItem.java:53) ~[MineableSpawners-4.4.0.jar:?]
        at de.tr7zw.nbtapi.NBTReflectionUtil.setData(NBTReflectionUtil.java:588) ~[MineableSpawners-4.4.0.jar:?]
        at de.tr7zw.nbtapi.NBTCompound.setString(NBTCompound.java:102) ~[MineableSpawners-4.4.0.jar:?]
        at nl.maartenvr98.mineablespawners.api.API.getSpawnerFromEntityType(API.java:72) ~[MineableSpawners-4.4.0.jar:?]
        at nl.maartenvr98.mineablespawners.listeners.SpawnerMineListener.giveSpawner(SpawnerMineListener.java:241) ~[MineableSpawners-4.4.0.jar:?]
        at nl.maartenvr98.mineablespawners.listeners.SpawnerMineListener.onSpawnerMine(SpawnerMineListener.java:96) ~[MineableSpawners-4.4.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor22.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:git-Paper-20]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:400) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:354) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:314) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1678) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:34) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:8) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.jar:git-Paper-20]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1412) ~[paper-1.18.jar:git-Paper-20]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.jar:git-Paper-20]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1390) ~[paper-1.18.jar:git-Paper-20]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1383) ~[paper-1.18.jar:git-Paper-20]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:110) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1517) ~[paper-1.18.jar:git-Paper-20]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1263) ~[paper-1.18.jar:git-Paper-20]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.jar:git-Paper-20]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: de.tr7zw.nbtapi.NbtApiException: Method not loaded! 'NMSITEM_GETTAG'
        at de.tr7zw.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:160) ~[MineableSpawners-4.4.0.jar:?]
        at de.tr7zw.nbtapi.NBTReflectionUtil.getItemRootNBTTagCompound(NBTReflectionUtil.java:122) ~[MineableSpawners-4.4.0.jar:?]
        ... 31 more`

`[22:31:52 INFO]: [NBTAPI] [NBTAPI] Found Spigot: v1_18_R1! Trying to find NMS support
[22:31:52 WARN]: [NBTAPI] [NBTAPI] Wasn't able to find NMS Support! Some functions may not work!
[22:31:52 INFO]: [NBTAPI] [NBTAPI] Found Gson: class com.google.gson.Gson
[22:31:52 INFO]: [MineableSpawners] [STDOUT] [NBTAPI] Unable to find the method 'setFloat' in 'NBTTagCompound' Enum: COMPOUND_SET_FLOAT
[22:31:52 INFO]: [MineableSpawners] [STDOUT] [NBTAPI] Unable to find the method 'setString' in 'NBTTagCompound' Enum: COMPOUND_SET_STRING
[22:31:52 INFO]: [MineableSpawners] [STDOUT] [NBTAPI] Unable to find the method 'setInt' in 'NBTTagCompound' Enum: COMPOUND_SET_INT
[22:31:52 INFO]: [MineableSpawners] [STDOUT] [NBTAPI] Unable to find the method 'setByteArray' in 'NBTTagCompound' Enum: COMPOUND_SET_BYTEARRAY
[22:31:52 INFO]: [MineableSpawners] [STDOUT] [NBTAPI] Unable to find the method 'setIntArray' in 'NBTTagCompound' Enum: COMPOUND_SET_INTARRAY
[22:31:52 INFO]: [MineableSpawners] [STDOUT] [NBTAPI] Unable to find the method 'setLong' in 'NBTTagCompound' Enum: COMPOUND_SET_LONG
[22:31:52 INFO]: [MineableSpawners] [STDOUT] [NBTAPI] Unable to find the method 'setShort' in 'NBTTagCompound' Enum: COMPOUND_SET_SHORT
[22:31:52 INFO]: [MineableSpawners] [STDOUT] [NBTAPI] Unable to find the method 'setByte' in 'NBTTagCompound' Enum: COMPOUND_SET_BYTE
[22:31:52 INFO]: [MineableSpawners] [STDOUT] [NBTAPI] Unable to find the method 'setDouble' in 'NBTTagCompound' Enum: COMPOUND_SET_DOUBLE
[22:31:52 INFO]: [MineableSpawners] [STDOUT] [NBTAPI] Unable to find the method 'setBoolean' in 'NBTTagCompound' Enum: COMPOUND_SET_BOOLEAN
[22:31:52 INFO]: [MineableSpawners] [STDOUT] [NBTAPI] Unable to find the method 'set' in 'NBTTagCompound' Enum: COMPOUND_SET
[22:31:52 INFO]: [MineableSpawners] [STDOUT] [NBTAPI] Unable to find the method 'get' in 'NBTTagCompound' Enum: COMPOUND_GET
[22:31:52 INFO]: [MineableSpawners] [STDOUT] [NBTAPI] Unable to find the method 'getList' in 'NBTTagCompound' Enum: COMPOUND_GET_LIST
[22:31:52 INFO]: [MineableSpawners] [STDOUT] [NBTAPI] Unable to find the method 'getFloat' in 'NBTTagCompound' Enum: COMPOUND_GET_FLOAT
[22:31:52 INFO]: [MineableSpawners] [STDOUT] [NBTAPI] Unable to find the method 'getString' in 'NBTTagCompound' Enum: COMPOUND_GET_STRING
[22:31:52 INFO]: [MineableSpawners] [STDOUT] [NBTAPI] Unable to find the method 'getInt' in 'NBTTagCompound' Enum: COMPOUND_GET_INT
[22:31:52 INFO]: [MineableSpawners] [STDOUT] [NBTAPI] Unable to find the method 'getByteArray' in 'NBTTagCompound' Enum: COMPOUND_GET_BYTEARRAY
[22:31:52 INFO]: [MineableSpawners] [STDOUT] [NBTAPI] Unable to find the method 'getIntArray' in 'NBTTagCompound' Enum: COMPOUND_GET_INTARRAY
[22:31:52 INFO]: [MineableSpawners] [STDOUT] [NBTAPI] Unable to find the method 'getLong' in 'NBTTagCompound' Enum: COMPOUND_GET_LONG
[22:31:52 INFO]: [MineableSpawners] [STDOUT] [NBTAPI] Unable to find the method 'getShort' in 'NBTTagCompound' Enum: COMPOUND_GET_SHORT
[22:31:52 INFO]: [MineableSpawners] [STDOUT] [NBTAPI] Unable to find the method 'getByte' in 'NBTTagCompound' Enum: COMPOUND_GET_BYTE
[22:31:52 INFO]: [MineableSpawners] [STDOUT] [NBTAPI] Unable to find the method 'getDouble' in 'NBTTagCompound' Enum: COMPOUND_GET_DOUBLE
[22:31:52 INFO]: [MineableSpawners] [STDOUT] [NBTAPI] Unable to find the method 'getBoolean' in 'NBTTagCompound' Enum: COMPOUND_GET_BOOLEAN
[22:31:52 INFO]: [MineableSpawners] [STDOUT] [NBTAPI] Unable to find the method 'getCompound' in 'NBTTagCompound' Enum: COMPOUND_GET_COMPOUND
[22:31:52 INFO]: [MineableSpawners] [STDOUT] [NBTAPI] Unable to find the method 'getTag' in 'ItemStack' Enum: NMSITEM_GETTAG
[22:31:52 INFO]: [MineableSpawners] [STDOUT] [NBTAPI] Unable to find the method 'save' in 'ItemStack' Enum: NMSITEM_SAVE
[22:31:52 INFO]: [MineableSpawners] [STDOUT] [NBTAPI] Unable to find the method 'remove' in 'NBTTagCompound' Enum: COMPOUND_REMOVE_KEY
[22:31:52 INFO]: [MineableSpawners] [STDOUT] [NBTAPI] Unable to find the method 'hasKey' in 'NBTTagCompound' Enum: COMPOUND_HAS_KEY
[22:31:52 INFO]: [MineableSpawners] [STDOUT] [NBTAPI] Unable to find the method 'getKeys' in 'NBTTagCompound' Enum: COMPOUND_GET_KEYS
[22:31:52 INFO]: [MineableSpawners] [STDOUT] [NBTAPI] Unable to find the method 'getKeys' in 'NBTTagCompound' Enum: LISTCOMPOUND_GET_KEYS
[22:31:52 INFO]: [MineableSpawners] [STDOUT] [NBTAPI] Unable to find the method 'set' in 'NBTTagList' Enum: LIST_SET
[22:31:52 INFO]: [MineableSpawners] [STDOUT] [NBTAPI] Unable to find the method 'add' in 'NBTTagList' Enum: LIST_ADD
[22:31:52 INFO]: [MineableSpawners] [STDOUT] [NBTAPI] Unable to find the method 'getString' in 'NBTTagList' Enum: LIST_GET_STRING
[22:31:52 INFO]: [MineableSpawners] [STDOUT] [NBTAPI] Unable to find the method 'setTag' in 'ItemStack' Enum: ITEMSTACK_SET_TAG
[22:31:52 INFO]: [MineableSpawners] [STDOUT] [NBTAPI] Unable to find the method 'getTileEntity' in 'WorldServer' Enum: NMS_WORLD_GET_TILEENTITY
[22:31:52 INFO]: [MineableSpawners] [STDOUT] [NBTAPI] Unable to find the method 'removeTileEntity' in 'WorldServer' Enum: NMS_WORLD_REMOVE_TILEENTITY
[22:31:52 INFO]: [MineableSpawners] [STDOUT] [NBTAPI] Unable to find the method 'save' in 'TileEntity' Enum: TILEENTITY_GET_NBT
[22:31:52 INFO]: [MineableSpawners] [STDOUT] [NBTAPI] Unable to find the method 'load' in 'TileEntity' Enum: TILEENTITY_SET_NBT
[22:31:52 INFO]: [MineableSpawners] [STDOUT] [NBTAPI] Unable to find the method 'getBlock' in 'TileEntity' Enum: TILEENTITY_GET_BLOCKDATA
[22:31:52 INFO]: [MineableSpawners] [STDOUT] [NBTAPI] Unable to find the method 'load' in 'Entity' Enum: NMS_ENTITY_SET_NBT
[22:31:52 INFO]: [MineableSpawners] [STDOUT] [NBTAPI] Unable to find the method 'save' in 'Entity' Enum: NMS_ENTITY_GET_NBT
[22:31:52 INFO]: [MineableSpawners] [STDOUT] [NBTAPI] Unable to find the method 'getSaveID' in 'Entity' Enum: NMS_ENTITY_GETSAVEID
[22:31:52 INFO]: [MineableSpawners] [STDOUT] [NBTAPI] Unable to find the method 'parse' in 'MojangsonParser' Enum: PARSE_NBT
[22:31:52 INFO]: [MineableSpawners] [STDOUT] [NBTAPI] Unable to find the method 'keySet' in 'RegistryMaterials' Enum: REGISTRYMATERIALS_KEYSET
[22:31:52 INFO]: [MineableSpawners] [STDOUT] [NBTAPI] Unable to find the method 'get' in 'RegistryMaterials' Enum: REGISTRYMATERIALS_GET
[22:31:52 INFO]: [MineableSpawners] [STDOUT] [NBTAPI] Unable to find the method 'getKey' in 'RegistryMaterials' Enum: REGISTRYMATERIALS_GETKEY
[22:31:52 INFO]: [MineableSpawners] [STDOUT] [NBTAPI] Unable to find the method 'deserialize' in 'GameProfileSerializer' Enum: GAMEPROFILE_DESERIALIZE
[22:31:52 INFO]: [MineableSpawners] [STDOUT] [NBTAPI] Unable to find the method 'serialize' in 'GameProfileSerializer' Enum: GAMEPROFILE_SERIALIZE
[22:31:53 INFO]: [NBTAPI] [NBTAPI] The NBT-API seems to be up-to-date!`

**Comment by tr7zw** [comment]
https://www.curseforge.com/minecraft/bukkit-plugins/nbt-api/files/3541737
