### ISSUE TITLE
Stack trace erroneously checking for updates

### ISSUE THREAD

**Issue by SlimeDog** [tr7zw/Item-NBT-API#163]
Spigot 1.18.1-3443 (and previous)
NBTAPI 2.9.2-b219
HeadsPluginAPI 3.0.1

Update checks are blocked at the network level (we have our own update-checker).
Dev states that HeadsPluginAPI does not check for updates itself.

plugins/NBTAPI/config.yml
```
silentquickstart: false
silentstart: false
nbtInjector:
  enabled: false
bStats:
  enabled: true
updateCheck:
  enabled: false
```

On server start-up
```
[09:46:02] [Thread-29/WARN]: [NBTAPI] Error while checking for updates!
java.net.SocketTimeoutException: Connection timed out
        at me.lucko.networkinterceptor.interceptors.ProxySelectorInterceptor$LoggingSelector.select(ProxySelectorInterceptor.java:65) ~[NetworkInterceptor-3.2.1.jar:?] 
        at com.github.games647.lagmonitor.listener.BlockingConnectionSelector.select(BlockingConnectionSelector.java:33) ~[LagMonitor-1.17.2-b191.jar:?]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1232) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1118) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1116) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:712) ~[?:?]
        at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:962) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1115) ~[?:?]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1581) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1579) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:712) ~[?:?]
        at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:962) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1578) ~[?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[?:?]
        at com.github.cc007.headsplugin.nbtapi.utils.VersionChecker.checkForUpdates(VersionChecker.java:34) ~[HeadsPluginAPI-3.0.1.jar:?]
        at com.github.cc007.headsplugin.nbtapi.utils.MinecraftVersion.lambda$init$0(MinecraftVersion.java:125) ~[HeadsPluginAPI-3.0.1.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by tr7zw** [comment]
Gonna cut out the stacktrace and just keep the message, so it's a oneliner instead of a useless wall of text. And if HeadsPluginAPI shades the nbtapi, that config file is the incorrect one.

**Comment by SlimeDog** [comment]
Thanks. I imagine that they shade NBTAPI, but I don't know for certain. If that is the case, how can they elide the update check?

**Comment by tr7zw** [comment]
Has to be set from the outside, so from the shading plugin. But since they probably have to update for 1.18.2 anyway, this entire thing will be folded into a one-liner just stating that the connection timed out.

**Comment by SlimeDog** [comment]
Thanks.
