### ISSUE TITLE
1.18.2 compability

### ISSUE THREAD

**Issue by sphings79** [tr7zw/Item-NBT-API#164]
```
[15:28:04 WARN]: [NBTAPI] [NBTAPI] This Server-Version(v1_18_R2) is not supported by this NBT-API Version(2.9.1) located at fr.aerwyn81.headblocks.bukkit.shaded.nbtapi.utils.MinecraftVersion. The NBT-API will try to work as good as it can! Some functions may not work!
[15:28:04 INFO]: [NBTAPI] [NBTAPI] Found Gson: class com.google.gson.Gson
[15:28:04 WARN]: [NBTAPI] [NBTAPI] Error while trying to resolve the class 'inventory.CraftItemStack'!
java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_18_R1.inventory.CraftItemStack
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:375) ~[?:?]
        at fr.aerwyn81.headblocks.bukkit.shaded.nbtapi.utils.nmsmappings.ClassWrapper.<init>(ClassWrapper.java:75) ~[HeadBlocks-1.6.1.jar:?]
        at fr.aerwyn81.headblocks.bukkit.shaded.nbtapi.utils.nmsmappings.ClassWrapper.<init>(ClassWrapper.java:55) ~[HeadBlocks-1.6.1.jar:?]
        at fr.aerwyn81.headblocks.bukkit.shaded.nbtapi.utils.nmsmappings.ClassWrapper.<clinit>(ClassWrapper.java:17) ~[HeadBlocks-1.6.1.jar:?]
        at fr.aerwyn81.headblocks.bukkit.shaded.nbtapi.utils.nmsmappings.ReflectionMethod.<clinit>(ReflectionMethod.java:23) ~[HeadBlocks-1.6.1.jar:?]
        at fr.aerwyn81.headblocks.bukkit.shaded.nbtapi.NBTCompound.setBoolean(NBTCompound.java:384) ~[HeadBlocks-1.6.1.jar:?]
        at fr.aerwyn81.headblocks.handlers.HeadHandler.loadHeads(HeadHandler.java:165) ~[HeadBlocks-1.6.1.jar:?]
        at fr.aerwyn81.headblocks.handlers.HeadHandler.loadConfiguration(HeadHandler.java:54) ~[HeadBlocks-1.6.1.jar:?]
        at fr.aerwyn81.headblocks.HeadBlocks.onEnable(HeadBlocks.java:120) ~[HeadBlocks-1.6.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[paper-1.18.2.jar:git-Paper-220]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.18.2.jar:git-Paper-220]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:666) ~[paper-1.18.2.jar:git-Paper-220]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:433) ~[paper-1.18.2.jar:git-Paper-220]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-220]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.18.2.jar:git-Paper-220]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-220]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:28:04 WARN]: [NBTAPI] [NBTAPI] Error while trying to resolve the class 'inventory.CraftMetaItem'!
java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_18_R1.inventory.CraftMetaItem
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:375) ~[?:?]
        at fr.aerwyn81.headblocks.bukkit.shaded.nbtapi.utils.nmsmappings.ClassWrapper.<init>(ClassWrapper.java:75) ~[HeadBlocks-1.6.1.jar:?]
        at fr.aerwyn81.headblocks.bukkit.shaded.nbtapi.utils.nmsmappings.ClassWrapper.<init>(ClassWrapper.java:55) ~[HeadBlocks-1.6.1.jar:?]
        at fr.aerwyn81.headblocks.bukkit.shaded.nbtapi.utils.nmsmappings.ClassWrapper.<clinit>(ClassWrapper.java:18) ~[HeadBlocks-1.6.1.jar:?]
        at fr.aerwyn81.headblocks.bukkit.shaded.nbtapi.utils.nmsmappings.ReflectionMethod.<clinit>(ReflectionMethod.java:23) ~[HeadBlocks-1.6.1.jar:?]
        at fr.aerwyn81.headblocks.bukkit.shaded.nbtapi.NBTCompound.setBoolean(NBTCompound.java:384) ~[HeadBlocks-1.6.1.jar:?]
        at fr.aerwyn81.headblocks.handlers.HeadHandler.loadHeads(HeadHandler.java:165) ~[HeadBlocks-1.6.1.jar:?]
        at fr.aerwyn81.headblocks.handlers.HeadHandler.loadConfiguration(HeadHandler.java:54) ~[HeadBlocks-1.6.1.jar:?]
        at fr.aerwyn81.headblocks.HeadBlocks.onEnable(HeadBlocks.java:120) ~[HeadBlocks-1.6.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[paper-1.18.2.jar:git-Paper-220]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.18.2.jar:git-Paper-220]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:666) ~[paper-1.18.2.jar:git-Paper-220]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:433) ~[paper-1.18.2.jar:git-Paper-220]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-220]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.18.2.jar:git-Paper-220]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-220]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:28:04 WARN]: [NBTAPI] [NBTAPI] Error while trying to resolve the class 'entity.CraftEntity'!
java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_18_R1.entity.CraftEntity
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:375) ~[?:?]
        at fr.aerwyn81.headblocks.bukkit.shaded.nbtapi.utils.nmsmappings.ClassWrapper.<init>(ClassWrapper.java:75) ~[HeadBlocks-1.6.1.jar:?]
        at fr.aerwyn81.headblocks.bukkit.shaded.nbtapi.utils.nmsmappings.ClassWrapper.<init>(ClassWrapper.java:55) ~[HeadBlocks-1.6.1.jar:?]
        at fr.aerwyn81.headblocks.bukkit.shaded.nbtapi.utils.nmsmappings.ClassWrapper.<clinit>(ClassWrapper.java:19) ~[HeadBlocks-1.6.1.jar:?]
        at fr.aerwyn81.headblocks.bukkit.shaded.nbtapi.utils.nmsmappings.ReflectionMethod.<clinit>(ReflectionMethod.java:23) ~[HeadBlocks-1.6.1.jar:?]
        at fr.aerwyn81.headblocks.bukkit.shaded.nbtapi.NBTCompound.setBoolean(NBTCompound.java:384) ~[HeadBlocks-1.6.1.jar:?]
        at fr.aerwyn81.headblocks.handlers.HeadHandler.loadHeads(HeadHandler.java:165) ~[HeadBlocks-1.6.1.jar:?]
        at fr.aerwyn81.headblocks.handlers.HeadHandler.loadConfiguration(HeadHandler.java:54) ~[HeadBlocks-1.6.1.jar:?]
        at fr.aerwyn81.headblocks.HeadBlocks.onEnable(HeadBlocks.java:120) ~[HeadBlocks-1.6.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[paper-1.18.2.jar:git-Paper-220]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.18.2.jar:git-Paper-220]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:666) ~[paper-1.18.2.jar:git-Paper-220]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:433) ~[paper-1.18.2.jar:git-Paper-220]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-220]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.18.2.jar:git-Paper-220]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-220]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:28:04 WARN]: [NBTAPI] [NBTAPI] Error while trying to resolve the class 'CraftWorld'!
java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_18_R1.CraftWorld
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:375) ~[?:?]
        at fr.aerwyn81.headblocks.bukkit.shaded.nbtapi.utils.nmsmappings.ClassWrapper.<init>(ClassWrapper.java:75) ~[HeadBlocks-1.6.1.jar:?]
        at fr.aerwyn81.headblocks.bukkit.shaded.nbtapi.utils.nmsmappings.ClassWrapper.<init>(ClassWrapper.java:55) ~[HeadBlocks-1.6.1.jar:?]
        at fr.aerwyn81.headblocks.bukkit.shaded.nbtapi.utils.nmsmappings.ClassWrapper.<clinit>(ClassWrapper.java:20) ~[HeadBlocks-1.6.1.jar:?]
        at fr.aerwyn81.headblocks.bukkit.shaded.nbtapi.utils.nmsmappings.ReflectionMethod.<clinit>(ReflectionMethod.java:23) ~[HeadBlocks-1.6.1.jar:?]
        at fr.aerwyn81.headblocks.bukkit.shaded.nbtapi.NBTCompound.setBoolean(NBTCompound.java:384) ~[HeadBlocks-1.6.1.jar:?]
        at fr.aerwyn81.headblocks.handlers.HeadHandler.loadHeads(HeadHandler.java:165) ~[HeadBlocks-1.6.1.jar:?]
        at fr.aerwyn81.headblocks.handlers.HeadHandler.loadConfiguration(HeadHandler.java:54) ~[HeadBlocks-1.6.1.jar:?]
        at fr.aerwyn81.headblocks.HeadBlocks.onEnable(HeadBlocks.java:120) ~[HeadBlocks-1.6.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[paper-1.18.2.jar:git-Paper-220]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.18.2.jar:git-Paper-220]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:666) ~[paper-1.18.2.jar:git-Paper-220]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:433) ~[paper-1.18.2.jar:git-Paper-220]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-220]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.18.2.jar:git-Paper-220]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-220]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:28:04 WARN]: [NBTAPI] [NBTAPI] Error while trying to resolve the class 'persistence.CraftPersistentDataContainer'!
java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_18_R1.persistence.CraftPersistentDataContainer
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:375) ~[?:?]
        at fr.aerwyn81.headblocks.bukkit.shaded.nbtapi.utils.nmsmappings.ClassWrapper.<init>(ClassWrapper.java:75) ~[HeadBlocks-1.6.1.jar:?]
        at fr.aerwyn81.headblocks.bukkit.shaded.nbtapi.utils.nmsmappings.ClassWrapper.<init>(ClassWrapper.java:55) ~[HeadBlocks-1.6.1.jar:?]
        at fr.aerwyn81.headblocks.bukkit.shaded.nbtapi.utils.nmsmappings.ClassWrapper.<clinit>(ClassWrapper.java:21) ~[HeadBlocks-1.6.1.jar:?]
        at fr.aerwyn81.headblocks.bukkit.shaded.nbtapi.utils.nmsmappings.ReflectionMethod.<clinit>(ReflectionMethod.java:23) ~[HeadBlocks-1.6.1.jar:?]
        at fr.aerwyn81.headblocks.bukkit.shaded.nbtapi.NBTCompound.setBoolean(NBTCompound.java:384) ~[HeadBlocks-1.6.1.jar:?]
        at fr.aerwyn81.headblocks.handlers.HeadHandler.loadHeads(HeadHandler.java:165) ~[HeadBlocks-1.6.1.jar:?]
        at fr.aerwyn81.headblocks.handlers.HeadHandler.loadConfiguration(HeadHandler.java:54) ~[HeadBlocks-1.6.1.jar:?]
        at fr.aerwyn81.headblocks.HeadBlocks.onEnable(HeadBlocks.java:120) ~[HeadBlocks-1.6.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[paper-1.18.2.jar:git-Paper-220]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.18.2.jar:git-Paper-220]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:666) ~[paper-1.18.2.jar:git-Paper-220]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:433) ~[paper-1.18.2.jar:git-Paper-220]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-220]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.18.2.jar:git-Paper-220]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-220]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:28:04 WARN]: [NBTAPI] [NBTAPI] Unable to find the method 'asNMSCopy' in 'null' Args: [class org.bukkit.inventory.ItemStack] Enum: ITEMSTACK_NMSCOPY
[15:28:04 WARN]: [NBTAPI] [NBTAPI] Unable to find the method 'asCraftMirror' in 'null' Args: [class net.minecraft.world.item.ItemStack] Enum: ITEMSTACK_BUKKITMIRROR
[15:28:04 WARN]: [NBTAPI] [NBTAPI] Unable to find the method 'getHandle' in 'null' Args: [] Enum: CRAFT_WORLD_GET_HANDLE[15:28:04 WARN]: [NBTAPI] [NBTAPI] Unable to find the method 'getHandle' in 'null' Args: [] Enum: CRAFT_ENTITY_GET_HANDLE
[15:28:04 WARN]: [NBTAPI] [NBTAPI] Unable to find the method 'toTagCompound' in 'null' Args: [] Enum: CRAFT_PERSISTENT_DATA_CONTAINER_TO_TAG
[15:28:04 WARN]: [NBTAPI] [NBTAPI] Unable to find the method 'getRaw' in 'null' Args: [] Enum: CRAFT_PERSISTENT_DATA_CONTAINER_GET_MAP
[15:28:04 WARN]: [NBTAPI] [NBTAPI] Unable to find the method 'putAll' in 'null' Args: [class net.minecraft.nbt.NBTTagCompound] Enum: CRAFT_PERSISTENT_DATA_CONTAINER_PUT_ALL
```
>  version
[15:34:33 INFO]: Checking version, please wait...
[15:34:33 INFO]: This server is running Paper version git-Paper-220 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 63aa4d3)
You are running the latest version
Previous version: git-Paper-216 (MC: 1.18.1)
> version nbtapi
[15:34:36 INFO]: NBTAPI version 2.9.2
[15:34:36 INFO]: Author: tr7zw

**Comment by vandon1** [comment]
+1 same issue and same Error trying to resolve messages in my log

**Comment by tr7zw** [comment]
Update to 2.9.2 https://ci.codemc.io/job/Tr7zw/job/Item-NBT-API/
