### ISSUE TITLE
NBT API doesn't work on spigot 1.8.8 - error

### ISSUE THREAD

**Issue by abhisantos** [tr7zw/Item-NBT-API#178]
I have tried all possible versions of NBT API , none of them work.

Running CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

The error is this

04.06 07:36:36 [Server] ERROR Could not load 'plugins/item-nbt-api-plugin-2.9.2.jar' in folder 'plugins'
04.06 07:36:36 [Server] INFO org.bukkit.plugin.InvalidPluginException: java.lang.IllegalArgumentException: Plugin already initialized!
04.06 07:36:36 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
04.06 07:36:36 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
04.06 07:36:36 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot.jar:git-Spigot-21fe707-e1ebe52]
04.06 07:36:36 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [spigot.jar:git-Spigot-21fe707-e1ebe52]
04.06 07:36:36 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot.jar:git-Spigot-21fe707-e1ebe52]
04.06 07:36:36 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-21fe707-e1ebe52]
04.06 07:36:36 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
04.06 07:36:36 [Server] INFO Caused by: java.lang.IllegalArgumentException: Plugin already initialized!
04.06 07:36:36 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:122) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
04.06 07:36:36 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:66) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
04.06 07:36:36 [Server] INFO at de.tr7zw.nbtapi.plugin.NBTAPI.<init>(Unknown Source) ~[?:?]
04.06 07:36:36 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_292]
04.06 07:36:36 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_292]
04.06 07:36:36 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_292]
04.06 07:36:36 [Server] INFO at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_292]
04.06 07:36:36 [Server] INFO at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_292]
04.06 07:36:36 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
04.06 07:36:37 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
04.06 07:36:37 [Server] INFO ... 6 more
04.06 07:36:37 [Server] INFO Caused by: java.lang.IllegalStateException: Initial initialization
04.06 07:36:37 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:125) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
04.06 07:36:37 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:66) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
04.06 07:36:37 [Server] INFO at com.dont.licensesystem.Terminal.<init>(Unknown Source) ~[?:?]
04.06 07:36:37 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_292]
04.06 07:36:37 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_292]
04.06 07:36:37 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_292]
04.06 07:36:37 [Server] INFO at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_292]
04.06 07:36:37 [Server] INFO at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_292]
04.06 07:36:37 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
04.06 07:36:37 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
04.06 07:36:37 [Server] INFO ... 6 more

**Comment by tr7zw** [comment]
``04.06 07:36:36 [Server] INFO org.bukkit.plugin.InvalidPluginException: java.lang.IllegalArgumentException: Plugin already initialized!`` presumably the plugin is already loaded? Don't use reload/other plugins to load the mod, correctly restart your server!
