### ISSUE TITLE
Problem with API

### ISSUE THREAD

**Issue by pawelkuwa** [tr7zw/Item-NBT-API#251]
So i got this problem
```
[03:02:45] [Server thread/ERROR]: Could not pass event InventoryClickEvent to wGuildPanel v1.1
me.wisnia.panel.nbtapi.nbtapi.NbtApiException: [?]Error while calling the method 'putString(java.lang.String,java.lang.String)', loaded: true, Enum: COMPOUND_SET_STRING Passed Class: class java.lang.Boolean
	at me.wisnia.panel.nbtapi.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:185) ~[wGuildPanel.jar:?]
	at me.wisnia.panel.nbtapi.nbtapi.NBTReflectionUtil.setData(NBTReflectionUtil.java:611) ~[wGuildPanel.jar:?]
	at me.wisnia.panel.nbtapi.nbtapi.NBTCompound.setString(NBTCompound.java:102) ~[wGuildPanel.jar:?]
	at me.wisnia.panel.Inventory.InventoryCreator.fillMembersPanel(InventoryCreator.java:266) ~[wGuildPanel.jar:?]
	at me.wisnia.panel.Inventory.InventoryCreator.getMembersPanel(InventoryCreator.java:185) ~[wGuildPanel.jar:?]
	at me.wisnia.panel.InventoryListener.PanelListener.onPanelClick(PanelListener.java:71) ~[wGuildPanel.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor242.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:git-Purpur-2062]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3334) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1365) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1342) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1335) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1313) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1201) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: object is not an instance of declaring class
	at jdk.internal.reflect.DirectMethodHandleAccessor.checkReceiver(DirectMethodHandleAccessor.java:202) ~[?:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:100) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at me.wisnia.panel.nbtapi.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:183) ~[wGuildPanel.jar:?]
	... 29 more
```
	
during execute this code
```
            NBTItem nbtItem = new NBTItem(item);
            nbtItem.setString("player", members.get(i).getName());
            item = nbtItem.getItem();
            gui.setItem(slot, item);
```

**Comment by pawelkuwa** [comment]
method getName used on list members returns String

**Comment by tr7zw** [comment]
Sorry didn't see it in time. This is a shaded version, most likely just outdated for the server's mc version.

**Comment by tr7zw** [comment]
Closing as inactive.
