### ISSUE TITLE
Error during 'EmptyItemTest' test!

### ISSUE THREAD

**Issue by Fikula** [tr7zw/Item-NBT-API#254]
Hello everyone,
since I updated to the last NBTAPI version (v2.12.0), I'll keep getting this error:

[Server thread/WARN]: [NBTAPI] Error during 'EmptyItemTest' test!
de.tr7zw.nbtapi.NbtApiException: [?][2.12.0]Item reported to have data
	at de.tr7zw.nbtapi.plugin.tests.items.EmptyItemTest.test(EmptyItemTest.java:18) ~[item-nbt-api-plugin-2.12.0.jar:?]
	at de.tr7zw.nbtapi.plugin.NBTAPI.onEnable(NBTAPI.java:220) ~[item-nbt-api-plugin-2.12.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.19.4.jar:git-Purpur-1982]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.19.4.jar:git-Purpur-1982]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:572) ~[purpur-1.19.4.jar:git-Purpur-1982]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:483) ~[purpur-1.19.4.jar:git-Purpur-1982]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:643) ~[purpur-1.19.4.jar:git-Purpur-1982]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:442) ~[purpur-1.19.4.jar:git-Purpur-1982]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.19.4.jar:git-Purpur-1982]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1120) ~[purpur-1.19.4.jar:git-Purpur-1982]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1982]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[Server thread/INFO]: [NBTAPI] EmptyItemTest: [?][2.12.0]Item reported to have data
[Server thread/WARN]: [NBTAPI] WARNING! This version of NBT-API seems to be broken with your Spigot version! Plugins that don't check properly may throw Exeptions, crash or have unexpected behaviors!

I am using a Purpur Server, version 1.19.4 (Build 1982).

I don't kwow much about coding, still learning, but I experience a duplication glitch on my server and I think it's because of this. If you need some more information to solve this "issue", please ask.

Thanks :)

**Comment by tr7zw** [comment]
Ah crap right, someone also reported that for 1.19. Not sure what makes 1.19 different, will have to look into it.

**Comment by Fikula** [comment]
Okay, thank you for your worldrecord-fast reply.
Then I have to ask other developers for other plugins.
Bye :D

**Comment by tr7zw** [comment]
I'll fix it tonight, whatever broke there.
