### ISSUE TITLE
broken with Paper with CB packge relocation

### ISSUE THREAD

**Issue by YuanYuanOwO** [tr7zw/Item-NBT-API#271]
https://forums.papermc.io/threads/important-dev-psa-future-removal-of-cb-package-relocation.1106/
Here is the error
```
[20:07:34] [Server thread/ERROR]: [NBTAPI] Error initializing plugin 'item-nbt-api-plugin-2.12.2.jar' in folder 'plugins\.paper-remapped' (Is it up to date?)
java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
	at de.tr7zw.nbtapi.utils.MinecraftVersion.getVersion(MinecraftVersion.java:111) ~[item-nbt-api-plugin-2.12.2.jar:?]
	at de.tr7zw.nbtapi.utils.MinecraftVersion.isAtLeastVersion(MinecraftVersion.java:88) ~[item-nbt-api-plugin-2.12.2.jar:?]
	at de.tr7zw.nbtapi.plugin.NBTAPI.onLoad(NBTAPI.java:112) ~[item-nbt-api-plugin-2.12.2.jar:?]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
	at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:507) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:274) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1133) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by tr7zw** [comment]
Already fixed in the dev builds.
