### ISSUE TITLE
v1_13_R2 ReflectionMethod error

### ISSUE THREAD

**Issue by langwan** [tr7zw/Item-NBT-API#28]
[11:49:31 INFO]: [NBTAPI] Found Spigot: v1_13_R2! Trying to find NMS support
[11:49:31 INFO]: [NBTAPI] NMS support 'MC1_13_R2' loaded!
[11:49:31 WARN]: java.lang.NullPointerException
[11:49:31 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:49:31 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[11:49:31 WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:49:31 WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[11:49:31 WARN]: 	at de.tr7zw.itemnbtapi.ReflectionMethod.run(ReflectionMethod.java:97)
[11:49:31 WARN]: 	at de.tr7zw.itemnbtapi.NBTReflectionUtil.getTileEntityNBTTagCompound(NBTReflectionUtil.java:125)
[11:49:31 WARN]: 	at de.tr7zw.itemnbtapi.NBTTileEntity.getCompound(NBTTileEntity.java:15)
[11:49:31 WARN]: 	at de.tr7zw.itemnbtapi.NBTReflectionUtil.getData(NBTReflectionUtil.java:339)
[11:49:31 WARN]: 	at de.tr7zw.itemnbtapi.NBTCompound.hasKey(NBTCompound.java:135)
[11:49:31 WARN]: 	at com.peterluo.mc.server.player.data.PlayerDataItem.addBreak(PlayerDataItem.java:153)
[11:49:31 WARN]: 	at com.peterluo.mc.server.player.data.PlayerDataListener.onBlockBreakEvent(PlayerDataListener.java:46)
[11:49:31 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:49:31 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[11:49:31 WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:49:31 WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[11:49:31 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304)
[11:49:31 WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[11:49:31 WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[11:49:31 WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[11:49:31 WARN]: 	at net.minecraft.server.v1_13_R2.PlayerInteractManager.breakBlock(PlayerInteractManager.java:292)
[11:49:31 WARN]: 	at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:123)
[11:49:31 WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1167)
[11:49:31 WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:40)
[11:49:31 WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:10)
[11:49:31 WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10)
[11:49:31 WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[11:49:31 WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[11:49:31 WARN]: 	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
[11:49:31 WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900)
[11:49:31 WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[11:49:31 WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835)
[11:49:31 WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733)
[11:49:31 WARN]: 	at java.lang.Thread.run(Thread.java:748)

**Comment by langwan** [comment]
[11:58:25 WARN]: java.lang.NullPointerException
[11:58:25 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:58:25 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[11:58:25 WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:58:25 WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[11:58:25 WARN]: 	at de.tr7zw.itemnbtapi.ReflectionMethod.run(ReflectionMethod.java:96)
[11:58:25 WARN]: 	at de.tr7zw.itemnbtapi.NBTReflectionUtil.getTileEntityNBTTagCompound(NBTReflectionUtil.java:125)
[11:58:25 WARN]: 	at de.tr7zw.itemnbtapi.NBTTileEntity.getCompound(NBTTileEntity.java:15)
[11:58:25 WARN]: 	at de.tr7zw.itemnbtapi.NBTReflectionUtil.getData(NBTReflectionUtil.java:339)
[11:58:25 WARN]: 	at de.tr7zw.itemnbtapi.NBTCompound.hasKey(NBTCompound.java:135)

**Comment by tr7zw** [comment]
Can you check on enable for errors, and what was the tile that got broken?

**Comment by tr7zw** [comment]
Hm well, this issue is still for version 1.x, and without further information I can't really do anything.
