### ISSUE TITLE
Error: TileTest - Spigotmc version 4361 - MC: 1.21.3 - 2.13.3-SNAPSHOT #404

### ISSUE THREAD

**Issue by EHCanadian** [tr7zw/Item-NBT-API#304]
MC v1.21.3 Spigotmc version 4361-Spigot-5eb8a94-6029040 (MC: 1.21.3)
NTPAPI v2.13.3-SNAPSHOT [#404]

```
[21:01:15] [Server thread/INFO]: [NBTAPI] Enabling NBTAPI v2.13.3-SNAPSHOT
[21:01:15] [Server thread/INFO]: [NBTAPI] Checking bindings...
[21:01:15] [Server thread/INFO]: [NBTAPI] All Classes were able to link!
[21:01:15] [Server thread/INFO]: [NBTAPI] All Methods were able to link!
[21:01:15] [Server thread/INFO]: [NBTAPI] Running NBT reflection test...
[21:01:17] [Server thread/WARN]: [NBTAPI] Error during 'TileTest' test!
de.tr7zw.nbtapi.NbtApiException: [?][2.13.3-SNAPSHOT]Wasn't able to use NBTTiles!
	at de.tr7zw.nbtapi.plugin.tests.tiles.TileTest.test(TileTest.java:43) ~[?:?]
	at de.tr7zw.nbtapi.plugin.NBTAPI.onEnable(NBTAPI.java:193) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267) ~[spigot-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:492) ~[spigot-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_21_R2.CraftServer.enablePlugin(CraftServer.java:579) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4361-Spigot-5eb8a94-6029040]
	at org.bukkit.craftbukkit.v1_21_R2.CraftServer.enablePlugins(CraftServer.java:493) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4361-Spigot-5eb8a94-6029040]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:656) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4361-Spigot-5eb8a94-6029040]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:441) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4361-Spigot-5eb8a94-6029040]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:268) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4361-Spigot-5eb8a94-6029040]
	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1032) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4361-Spigot-5eb8a94-6029040]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4361-Spigot-5eb8a94-6029040]
	at java.base/java.lang.Thread.run(Thread.java:1575) [?:?]
Caused by: de.tr7zw.nbtapi.NbtApiException: [?][2.13.3-SNAPSHOT]The Lock wasn't successfully set.
	at de.tr7zw.nbtapi.plugin.tests.tiles.TileTest.test(TileTest.java:38) ~[?:?]
	... 12 more
[21:01:17] [Server thread/INFO]: [NBTAPI] TileTest: [?][2.13.3-SNAPSHOT]Wasn't able to use NBTTiles!
[21:01:17] [Server thread/WARN]: [NBTAPI] WARNING! This version of NBT-API seems to be broken with your Spigot version! Plugins that don't check properly may throw Exeptions, crash or have unexpected behaviors!
```

**Comment by tr7zw** [comment]
Ah, the lock name/functionality was changed. You can ignore that, that is just a bug in the test for 1.21.3, not an actual issue.
