### ISSUE TITLE
APIMetrics cannot register..

### ISSUE THREAD

**Issue by MisterZet** [tr7zw/Item-NBT-API#59]
`java.lang.IllegalStateException: ServiceRegisterEvent cannot be triggered asynchronously from another thread.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:511) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.plugin.SimpleServicesManager.register(SimpleServicesManager.java:59) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.squidstudios.mfhoppers.util.nbt.utils.ApiMetricsLite.<init>(ApiMetricsLite.java:134) ~[MFHoppers-3.12-v1.14.jar:?]
        at net.squidstudios.mfhoppers.util.nbt.utils.MinecraftVersion.init(MinecraftVersion.java:86) [MFHoppers-3.12-v1.14.jar:?]
        at net.squidstudios.mfhoppers.util.nbt.utils.MinecraftVersion.getVersion(MinecraftVersion.java:79) [MFHoppers-3.12-v1.14.jar:?]
        at net.squidstudios.mfhoppers.util.nbt.utils.nmsmappings.ClassWrapper.<init>(ClassWrapper.java:50) [MFHoppers-3.12-v1.14.jar:?]
        at net.squidstudios.mfhoppers.util.nbt.utils.nmsmappings.ClassWrapper.<clinit>(ClassWrapper.java:35) [MFHoppers-3.12-v1.14.jar:?]
        at net.squidstudios.mfhoppers.util.nbt.utils.nmsmappings.ReflectionMethod.<clinit>(ReflectionMethod.java:20) [MFHoppers-3.12-v1.14.jar:?]
        at net.squidstudios.mfhoppers.util.nbt.NBTCompound.getByte(NBTCompound.java:152) [MFHoppers-3.12-v1.14.jar:?]
        at net.squidstudios.mfhoppers.tasks.TaskManager.runGrind(TaskManager.java:133) [MFHoppers-3.12-v1.14.jar:?]
        at net.squidstudios.mfhoppers.tasks.TaskManager$1.run(TaskManager.java:62) [MFHoppers-3.12-v1.14.jar:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_231]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_231]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]`

**Comment by tr7zw** [comment]
Ehhh the api got called async during the first call... Yea I'll look into fixing this 👍

**Comment by MisterZet** [comment]
Np, hope to see it fixed soon. Annoying error at the start 👍
